namespace Daqifi.Core.Device.SdCard
{
    /// <summary>
    /// Describes an SD-card logging session that was just started: the effective on-card file
    /// name (whether supplied by the caller or auto-generated by Core) and the format it is
    /// being written in. Returned by
    /// <see cref="ISdCardOperations.StartSdCardLoggingAsync(string, string, SdCardLogFormat, System.Threading.CancellationToken)"/>
    /// so callers can report, download, or later delete the log without re-deriving Core's
    /// naming convention.
    /// </summary>
    public sealed class SdCardLoggingSession
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SdCardLoggingSession"/> class.
        /// </summary>
        /// <param name="fileName">The effective on-card file name.</param>
        /// <param name="format">The logging format the file is written in.</param>
        public SdCardLoggingSession(string fileName, SdCardLogFormat format)
        {
            FileName = fileName;
            Format = format;
        }

        /// <summary>
        /// Gets the effective on-card file name — the value sent to the device, whether it was
        /// supplied by the caller or auto-generated as <c>log_YYYYMMDD_HHMMSS</c> with the
        /// format-appropriate extension.
        /// </summary>
        public string FileName { get; }

        /// <summary>
        /// Gets the logging format the file is written in.
        /// </summary>
        public SdCardLogFormat Format { get; }
    }
}
